// Complete list of 180+ languages with native names
export interface Language {
  code: string;
  name: string;
  nativeName: string;
}

export const languages: Language[] = [
  { code: "af", name: "Afrikaans", nativeName: "Afrikaans" },
  { code: "sq", name: "Albanian", nativeName: "Shqip" },
  { code: "am", name: "Amharic", nativeName: "አማርኛ" },
  { code: "ar", name: "Arabic", nativeName: "العربية" },
  { code: "hy", name: "Armenian", nativeName: "Հայերեն" },
  { code: "az", name: "Azerbaijani", nativeName: "Azərbaycan" },
  { code: "eu", name: "Basque", nativeName: "Euskara" },
  { code: "be", name: "Belarusian", nativeName: "Беларуская" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা" },
  { code: "bs", name: "Bosnian", nativeName: "Bosanski" },
  { code: "bg", name: "Bulgarian", nativeName: "Български" },
  { code: "my", name: "Burmese", nativeName: "မြန်မာ" },
  { code: "ca", name: "Catalan", nativeName: "Català" },
  { code: "ceb", name: "Cebuano", nativeName: "Cebuano" },
  { code: "ny", name: "Chichewa", nativeName: "Chichewa" },
  { code: "zh", name: "Chinese (Simplified)", nativeName: "中文(简体)" },
  { code: "zh-TW", name: "Chinese (Traditional)", nativeName: "中文(繁體)" },
  { code: "co", name: "Corsican", nativeName: "Corsu" },
  { code: "hr", name: "Croatian", nativeName: "Hrvatski" },
  { code: "cs", name: "Czech", nativeName: "Čeština" },
  { code: "da", name: "Danish", nativeName: "Dansk" },
  { code: "nl", name: "Dutch", nativeName: "Nederlands" },
  { code: "en", name: "English", nativeName: "English" },
  { code: "eo", name: "Esperanto", nativeName: "Esperanto" },
  { code: "et", name: "Estonian", nativeName: "Eesti" },
  { code: "fi", name: "Finnish", nativeName: "Suomi" },
  { code: "fr", name: "French", nativeName: "Français" },
  { code: "fy", name: "Frisian", nativeName: "Frysk" },
  { code: "gl", name: "Galician", nativeName: "Galego" },
  { code: "ka", name: "Georgian", nativeName: "ქართული" },
  { code: "de", name: "German", nativeName: "Deutsch" },
  { code: "el", name: "Greek", nativeName: "Ελληνικά" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી" },
  { code: "ht", name: "Haitian Creole", nativeName: "Kreyòl Ayisyen" },
  { code: "ha", name: "Hausa", nativeName: "Hausa" },
  { code: "haw", name: "Hawaiian", nativeName: "ʻŌlelo Hawaiʻi" },
  { code: "he", name: "Hebrew", nativeName: "עברית" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "hmn", name: "Hmong", nativeName: "Hmong" },
  { code: "hu", name: "Hungarian", nativeName: "Magyar" },
  { code: "is", name: "Icelandic", nativeName: "Íslenska" },
  { code: "ig", name: "Igbo", nativeName: "Igbo" },
  { code: "id", name: "Indonesian", nativeName: "Bahasa Indonesia" },
  { code: "ga", name: "Irish", nativeName: "Gaeilge" },
  { code: "it", name: "Italian", nativeName: "Italiano" },
  { code: "ja", name: "Japanese", nativeName: "日本語" },
  { code: "jv", name: "Javanese", nativeName: "Basa Jawa" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ" },
  { code: "kk", name: "Kazakh", nativeName: "Қазақ" },
  { code: "km", name: "Khmer", nativeName: "ខ្មែរ" },
  { code: "rw", name: "Kinyarwanda", nativeName: "Ikinyarwanda" },
  { code: "ko", name: "Korean", nativeName: "한국어" },
  { code: "ku", name: "Kurdish", nativeName: "Kurdî" },
  { code: "ky", name: "Kyrgyz", nativeName: "Кыргызча" },
  { code: "lo", name: "Lao", nativeName: "ລາວ" },
  { code: "la", name: "Latin", nativeName: "Latina" },
  { code: "lv", name: "Latvian", nativeName: "Latviešu" },
  { code: "lt", name: "Lithuanian", nativeName: "Lietuvių" },
  { code: "lb", name: "Luxembourgish", nativeName: "Lëtzebuergesch" },
  { code: "mk", name: "Macedonian", nativeName: "Македонски" },
  { code: "mg", name: "Malagasy", nativeName: "Malagasy" },
  { code: "ms", name: "Malay", nativeName: "Bahasa Melayu" },
  { code: "ml", name: "Malayalam", nativeName: "മലയാളം" },
  { code: "mt", name: "Maltese", nativeName: "Malti" },
  { code: "mi", name: "Maori", nativeName: "Te Reo Māori" },
  { code: "mr", name: "Marathi", nativeName: "मराठी" },
  { code: "mn", name: "Mongolian", nativeName: "Монгол" },
  { code: "ne", name: "Nepali", nativeName: "नेपाली" },
  { code: "no", name: "Norwegian", nativeName: "Norsk" },
  { code: "or", name: "Odia", nativeName: "ଓଡ଼ିଆ" },
  { code: "ps", name: "Pashto", nativeName: "پښتو" },
  { code: "fa", name: "Persian", nativeName: "فارسی" },
  { code: "pl", name: "Polish", nativeName: "Polski" },
  { code: "pt", name: "Portuguese", nativeName: "Português" },
  { code: "pt-BR", name: "Portuguese (Brazil)", nativeName: "Português (Brasil)" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
  { code: "ro", name: "Romanian", nativeName: "Română" },
  { code: "ru", name: "Russian", nativeName: "Русский" },
  { code: "sm", name: "Samoan", nativeName: "Gagana Sāmoa" },
  { code: "gd", name: "Scots Gaelic", nativeName: "Gàidhlig" },
  { code: "sr", name: "Serbian", nativeName: "Српски" },
  { code: "st", name: "Sesotho", nativeName: "Sesotho" },
  { code: "sn", name: "Shona", nativeName: "Shona" },
  { code: "sd", name: "Sindhi", nativeName: "سنڌي" },
  { code: "si", name: "Sinhala", nativeName: "සිංහල" },
  { code: "sk", name: "Slovak", nativeName: "Slovenčina" },
  { code: "sl", name: "Slovenian", nativeName: "Slovenščina" },
  { code: "so", name: "Somali", nativeName: "Soomaali" },
  { code: "es", name: "Spanish", nativeName: "Español" },
  { code: "su", name: "Sundanese", nativeName: "Basa Sunda" },
  { code: "sw", name: "Swahili", nativeName: "Kiswahili" },
  { code: "sv", name: "Swedish", nativeName: "Svenska" },
  { code: "tl", name: "Tagalog", nativeName: "Tagalog" },
  { code: "tg", name: "Tajik", nativeName: "Тоҷикӣ" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்" },
  { code: "tt", name: "Tatar", nativeName: "Татар" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు" },
  { code: "th", name: "Thai", nativeName: "ไทย" },
  { code: "tr", name: "Turkish", nativeName: "Türkçe" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "uk", name: "Ukrainian", nativeName: "Українська" },
  { code: "ur", name: "Urdu", nativeName: "اردو" },
  { code: "ug", name: "Uyghur", nativeName: "ئۇيغۇرچە" },
  { code: "uz", name: "Uzbek", nativeName: "Oʻzbek" },
  { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt" },
  { code: "cy", name: "Welsh", nativeName: "Cymraeg" },
  { code: "xh", name: "Xhosa", nativeName: "IsiXhosa" },
  { code: "yi", name: "Yiddish", nativeName: "ייִדיש" },
  { code: "yo", name: "Yoruba", nativeName: "Yorùbá" },
  { code: "zu", name: "Zulu", nativeName: "IsiZulu" },
  { code: "as", name: "Assamese", nativeName: "অসমীয়া" },
  { code: "ay", name: "Aymara", nativeName: "Aymar" },
  { code: "bm", name: "Bambara", nativeName: "Bamanankan" },
  { code: "bho", name: "Bhojpuri", nativeName: "भोजपुरी" },
  { code: "dv", name: "Dhivehi", nativeName: "ދިވެހި" },
  { code: "doi", name: "Dogri", nativeName: "डोगरी" },
  { code: "ee", name: "Ewe", nativeName: "Eʋegbe" },
  { code: "gn", name: "Guarani", nativeName: "Avañeʼẽ" },
  { code: "ilo", name: "Ilocano", nativeName: "Ilokano" },
  { code: "kri", name: "Krio", nativeName: "Krio" },
  { code: "lg", name: "Luganda", nativeName: "Luganda" },
  { code: "mai", name: "Maithili", nativeName: "मैथिली" },
  { code: "mni", name: "Meitei", nativeName: "ꯃꯤꯇꯩꯂꯣꯟ" },
  { code: "lus", name: "Mizo", nativeName: "Mizo ṭawng" },
  { code: "nso", name: "Sepedi", nativeName: "Sepedi" },
  { code: "om", name: "Oromo", nativeName: "Afaan Oromoo" },
  { code: "qu", name: "Quechua", nativeName: "Runasimi" },
  { code: "sa", name: "Sanskrit", nativeName: "संस्कृतम्" },
  { code: "ti", name: "Tigrinya", nativeName: "ትግርኛ" },
  { code: "ts", name: "Tsonga", nativeName: "Xitsonga" },
  { code: "tw", name: "Twi", nativeName: "Twi" },
  { code: "ak", name: "Akan", nativeName: "Akan" },
  { code: "ln", name: "Lingala", nativeName: "Lingála" },
  { code: "crs", name: "Seychellois Creole", nativeName: "Kreol Seselwa" },
  { code: "tn", name: "Tswana", nativeName: "Setswana" },
  { code: "wo", name: "Wolof", nativeName: "Wolof" },
  { code: "ks", name: "Kashmiri", nativeName: "कॉशुर" },
  { code: "kok", name: "Konkani", nativeName: "कोंकणी" },
  { code: "sat", name: "Santali", nativeName: "ᱥᱟᱱᱛᱟᱲᱤ" },
  { code: "ff", name: "Fula", nativeName: "Fulfulde" },
  { code: "rn", name: "Kirundi", nativeName: "Ikirundi" },
  { code: "sg", name: "Sango", nativeName: "Sängö" },
  { code: "ber", name: "Berber", nativeName: "ⵜⴰⵎⴰⵣⵉⵖⵜ" },
  { code: "chr", name: "Cherokee", nativeName: "ᏣᎳᎩ" },
  { code: "cr", name: "Cree", nativeName: "ᓀᐦᐃᔭᐍᐏᐣ" },
  { code: "hil", name: "Hiligaynon", nativeName: "Ilonggo" },
  { code: "war", name: "Waray", nativeName: "Winaray" },
  { code: "pag", name: "Pangasinan", nativeName: "Pangasinan" },
  { code: "pam", name: "Kapampangan", nativeName: "Kapampangan" },
  { code: "min", name: "Minangkabau", nativeName: "Baso Minang" },
  { code: "ace", name: "Acehnese", nativeName: "Bahsa Acèh" },
  { code: "ban", name: "Balinese", nativeName: "Basa Bali" },
  { code: "mad", name: "Madurese", nativeName: "Madhurâ" },
  { code: "bug", name: "Buginese", nativeName: "ᨅᨔ ᨕᨘᨁᨗ" },
  { code: "tpi", name: "Tok Pisin", nativeName: "Tok Pisin" },
  { code: "bi", name: "Bislama", nativeName: "Bislama" },
  { code: "fj", name: "Fijian", nativeName: "Na Vosa Vakaviti" },
  { code: "to", name: "Tongan", nativeName: "Lea Fakatonga" },
  { code: "ty", name: "Tahitian", nativeName: "Reo Tahiti" },
  { code: "mh", name: "Marshallese", nativeName: "Kajin M̧ajeļ" },
  { code: "niu", name: "Niuean", nativeName: "Ko e Vagahau Niuē" },
  { code: "tkl", name: "Tokelauan", nativeName: "Gagana Tokelau" },
  { code: "tvl", name: "Tuvaluan", nativeName: "Te Ggana Tuvalu" },
  { code: "gil", name: "Gilbertese", nativeName: "Taetae ni Kiribati" },
  { code: "nau", name: "Nauruan", nativeName: "Dorerin Naoero" },
  { code: "tet", name: "Tetum", nativeName: "Tetun" },
  { code: "tum", name: "Tumbuka", nativeName: "chiTumbuka" },
  { code: "ve", name: "Venda", nativeName: "Tshivenḓa" },
  { code: "ss", name: "Swati", nativeName: "SiSwati" },
  { code: "nr", name: "South Ndebele", nativeName: "IsiNdebele" },
  { code: "nd", name: "North Ndebele", nativeName: "IsiNdebele" },
  { code: "chy", name: "Cheyenne", nativeName: "Tsėhésenėstsestȯtse" },
  { code: "nv", name: "Navajo", nativeName: "Diné Bizaad" },
  { code: "oj", name: "Ojibwe", nativeName: "ᐊᓂᔑᓈᐯᒧᐎᓐ" },
  { code: "ik", name: "Inupiaq", nativeName: "Iñupiaq" },
];

export function getLanguageName(code: string): string {
  return languages.find(l => l.code === code)?.nativeName || code;
}

export function searchLanguages(query: string): Language[] {
  const q = query.toLowerCase();
  return languages.filter(
    l => l.name.toLowerCase().includes(q) || l.nativeName.toLowerCase().includes(q) || l.code.toLowerCase().includes(q)
  );
}
